// 定义属性映射
export const propertyMap = {
    'm': 'margin',
    'p': 'padding',
    'ml': 'margin-left',
    'mr': 'margin-right',
    'mb': 'margin-bottom',
    'mt': 'margin-top',
    'pl': 'padding-left',
    'pr': 'padding-right',
    'pb': 'padding-bottom',
    'pt': 'padding-top',
    'bdr': 'border-radius',
    'bw': 'border-width',
    't': 'top',
    'l': 'left',
    'r': 'right',
    'b': 'bottom',
    'w': 'width',
    'h': 'height',
    'nw': 'min-width',
    'nh': 'min-height',
    'mw': 'max-width',
    'mh': 'max-height',
    'fs': 'font-size',
    'mx': ['margin-left', 'margin-right'],
    'my': ['margin-top', 'margin-bottom'],
    'px': ['padding-left', 'padding-right'],
    'py': ['padding-top', 'padding-bottom'],
    'ls': 'letter-spacing',
    'ws': 'word-spacing',
    'lh': 'line-height',
    'zi': 'z-index',
    'op': 'opacity',
    'fw': 'font-weight',
    'ti': 'text-indent',
};